deployment:
  docker:
    cmd: minikube docker-env
  kubernetes:
    context: minikube
    configs:
      - kube/environments/dev/services.yaml
      - kube/environments/dev/deployments.yaml
    config-templates:
      - template: kube/environments/dev/templates/deployments.yaml
        target: kube/environments/dev/deployments.yaml
  images:
    - name: nginx-static-proxy
      location: app/nginx
      tags: latest
    - name: python-dependencies
      location: app/api
      dockerfile: dependencies.Dockerfile
      tags: "3.5"
    - name: flask-api
      location: app/api
      tags: latest
