deployment:
  docker:
    cmd: minikube docker-env
    repo: gcr.io/GOOGLE_PROJECT
    gcloud-push: true
  kubernetes:
    context: GOOGLE_CONTEXT
    configs:
      - kube/environments/prod/services.yaml
      - kube/environments/prod/deployments.yaml
      - kube/environments/prod/database.yaml
    config-templates:
      - template: kube/environments/prod/templates/deployments.yaml
        target: kube/environments/prod/deployments.yaml
  images:
    - name: nginx-static-proxy
      location: app/nginx
      tags: latest
    - name: letsencrypt-companion
      location: app/letsencrypt
      tags: latest
    - name: python-dependencies
      location: app/api
      dockerfile: dependencies.Dockerfile
      tags: "3.5"
    - name: flask-api
      location: app/api
      tags: latest
