deployment:
  docker-env:
    cmd: eval $(minikube docker-env)
    repo: gcr.io/GOOGLE_PROJECT
  kuberetes-env:
    context: GOOGLE_CONTEXT
    configs:
      - kube/environments/prod/services.yaml
      - kube/environments/prod/deployments.yaml
      - kube/environments/prod/database.yaml
    config-templates:
      - template: kube/environments/prod/templates/deployments.yaml
        target: kube/environments/prod/deployments.yaml
  images:
    - name: nginx-static-proxy
      location: app/nginx
      tags: latest
    - name: letsencrypt-companion
      location: app/letsencrypt
      tags: latest
    - name: python-dependencies
      location: app/api
      dockerfile: dependencies.Dockerfile
      tags: 2.7
    - name: flask-api
      location: app/api
      tags: latest
