apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: nginx
          image: {nginx-static-proxy}
          volumeMounts:
            - mountPath: /etc/nginx/letsencrypt/
              name: letsencrypt-certificates
              readOnly: true
            - mountPath: /letsencrypt/challenges/.well-known/acme-challenge/
              name: acme-challenge
              readOnly: true
        - name: letsencrypt
          image: {letsencrypt-companion}
          volumeMounts:
            - mountPath: /letsencrypt/challenges/.well-known/acme-challenge/
              name: acme-challenge
          env:
            - name: EMAIL
              value: MYEMAIL@EMAIL.COM
            - name: DOMAINS
              value: MYDOMAIN.COM
            - name: ACCEPT_TOS
              value: "yes"
            - name: LETSENCRYPT_ENDPOINT
              value: https://acme-staging.api.letsencrypt.org/directory
            - name: SECRET_NAME
              value: letsencrypt-certificates
            - name: RENEWAL_FREQUENCY
              value: 0 0 1 * *
        - name: flask
          image: {flask-api}
          env:
            - name: DATABASE
              value: postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: session-secret
                  key: session-secret
      volumes:
        - name: letsencrypt-certificates
          secret:
              secretName: letsencrypt-certificates
        - name: acme-challenge
          emptyDir: {{}}
